# Generated by Django 3.0.5 on 2020-05-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='p_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='auther_name',
            new_name='p_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='p_owner',
        ),
        migrations.AddField(
            model_name='product',
            name='p_c_date',
            field=models.DateTimeField(auto_now=True, verbose_name='创建日期'),
        ),
        migrations.AddField(
            model_name='product',
            name='p_type',
            field=models.CharField(default='1', max_length=5),
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
